# Generated by Django 3.2.10 on 2023-02-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_sports',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_random_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip',
        ),
    ]
