# Generated by Django 3.2.10 on 2023-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230211_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
