# Generated by Django 3.2.10 on 2023-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_token_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
