# Generated by Django 3.2.10 on 2023-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230211_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image_src',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
