# Generated by Django 3.2.10 on 2023-02-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230211_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
