# Generated by Django 3.2.10 on 2023-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_token_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['index_in_collection', 'id']},
        ),
        migrations.AddField(
            model_name='token',
            name='index_in_collection',
            field=models.IntegerField(default=0),
        ),
    ]
